server:
  port: 8081
  servlet:
    context-path: /bro

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/bro?serverTimezone=UTC
    username: root
    password: 1234
